# Generated by Django 6.0.3 on 2026-04-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='client_email',
        ),
        migrations.AddField(
            model_name='bill',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
